parameters:
    database_driver: pdo_mysql
    database_host: mytreneodb.cvl8bjsoyflz.eu-west-1.rds.amazonaws.com
    database_port: null
    database_name: treneo
    database_user: mytreneouser
    database_password: mytreneouser
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: c60b343b1ff4bf56b50b19de2be3cdfd4bfb2e70
    database_path: null
