_start:
    pattern:  /
    defaults: { _controller: MyTreneoBundle:Start:index }

_offer_add_form:
    pattern:  /offer/create/
    defaults: { _controller: MyTreneoBundle:Offer:showAddForm }
    requirements:
      _method: GET

_offer_create:
    pattern:  /offer/create/
    defaults: { _controller: MyTreneoBundle:Offer:create }
    requirements:
      _method: POST

_offer_show:
    pattern:  /{id}/{slug}/
    defaults: { _controller: MyTreneoBundle:Offer:show }
    requirements:
      _method: GET
      id: \d+

_comment_add:
    pattern:  /comment/add/{offer_id}
    defaults: { _controller: MyTreneoBundle:Comment:add }
    requirements:
      _method: POST
      offer_id: \d+

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
