# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
_start:
    pattern:  /
    defaults: { _controller: MyTreneoBundle:Start:index }

_offer_add_form:
    pattern:  /offer/create/
    defaults: { _controller: MyTreneoBundle:Offer:showAddForm }
    requirements:
      _method: GET

_offer_create:
    pattern:  /offer/create/
    defaults: { _controller: MyTreneoBundle:Offer:create }
    requirements:
      _method: POST

_offer_show_slug:
    pattern:  /{id}/{slug}/
    defaults: { _controller: MyTreneoBundle:Offer:show }
    requirements:
      _method: GET
      id: \d+
      slug: .+

_offer_show:
    pattern:  /{id}/
    defaults: { _controller: MyTreneoBundle:Offer:show }
    requirements:
      _method: GET
      id: \d+

_comment_add:
    pattern:  /comment/add/{offer_id}
    defaults: { _controller: MyTreneoBundle:Comment:add }
    requirements:
      _method: POST
      offer_id: \d+