_start:
    pattern:  /
    defaults: { _controller: MyTreneoBundle:Start:index }

_offer_add:
    pattern:  /submit/
    defaults: { _controller: MyTreneoBundle:Offer:add }

_offer_show:
    pattern:  /offer/{id}
    defaults: { _controller: MyTreneoBundle:Offer:show }
    requirements:
      _method: GET
      id: \d+

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
